In [56]:
import numpy as np

In [57]:
testing = True
input_filename = testing and 'input.test.txt' or 'input.txt'

data = []
with open(input_filename) as f:
    for line in f.readlines():
        data.append(line.strip())


In [74]:
a = np.matrix([list(map(int, x)) for x in data], dtype=int)
b = np.empty(a.shape, dtype=int)
b.fill(0)

n, m = a.shape
for i in range(n):
    imax = -1
    for j in range(m):
        if a[i, j] > imax:
            imax = a[i, j]

In [59]:
def day08_part1(data):
    data = np.matrix(list(list(map(int, x)) for x in data), dtype=int)
    mat = np.matrix.__doc__
    n, m = data.shape
    for i in range(n):
        for j in range(m):
            data[i, j]
    return data

In [60]:
def day08_part2(data):
    pass

In [61]:
result1 = day08_part1(data)
print('Result1: ', result1)
result2 = day08_part2(data)
print('Result2: ', result2)

Result1:  [[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
Result2:  None
